server:
  port: 80

spring:
    datasource:
        name: main
        url: jdbc:mysql://rm-bp1hgh468001k65g71o.mysql.rds.aliyuncs.com:3306/cns
        username: wangning113
        password: 3694Tara
         # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.edu.lnpu.cnsweb.web.model

mapper:
  mappers:  cn.edu.lnpu.cnsweb.web.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check\
QR_URL: http://192.168.191.3:8080/spot/detail?id=